# Site metadata
title: SITE_TITLE
keywords: SITE_KEYWORDS
description: SITE_DESCRIPTION

# Custom metadata - see https://help.github.com/articles/repository-metadata-on-github-pages/
# The ID of the Google Doc to be embedded.  
googledoc_id: GOOGLEDOC_ID
# Google Analytics code.
ga_code: GA_CODE

# Jekyll / GitHub Pages settings
baseurl: ""
markdown: kramdown
#exclude: ["README.md"]
sass:
  style: compact

# Don't use a GitHub Page theme by default.
#theme: jekyll-theme-minimal

