# Site settings
title: walthamstow.me
keywords: walthamstow,e17,community,london,john field
description: A springboard site for Walthamstow, Lomndon

# Custom metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/
googledoc_id: 1eDRE8QkbZO-GGAYzXCSDQfsz97DZtWqMJZDlbDQH_cU
ga_code: UA-94019156-1

# Build settings
markdown: kramdown
#exclude: ["README.md"]
sass:
  style: compressed
  
#theme: jekyll-theme-minimal
